// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventdb/eventpb/event.proto

package eventpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RecordedEvent contains all the data about a specific event.
type RecordedEvent struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	EventType            string   `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 []byte   `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordedEvent) Reset()         { *m = RecordedEvent{} }
func (m *RecordedEvent) String() string { return proto.CompactTextString(m) }
func (*RecordedEvent) ProtoMessage()    {}
func (*RecordedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3946c2c051896ffe, []int{0}
}

func (m *RecordedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordedEvent.Unmarshal(m, b)
}
func (m *RecordedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordedEvent.Marshal(b, m, deterministic)
}
func (m *RecordedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordedEvent.Merge(m, src)
}
func (m *RecordedEvent) XXX_Size() int {
	return xxx_messageInfo_RecordedEvent.Size(m)
}
func (m *RecordedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RecordedEvent proto.InternalMessageInfo

func (m *RecordedEvent) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RecordedEvent) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RecordedEvent) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *RecordedEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RecordedEvent) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordedEvent)(nil), "eventpb.RecordedEvent")
}

func init() { proto.RegisterFile("eventdb/eventpb/event.proto", fileDescriptor_3946c2c051896ffe) }

var fileDescriptor_3946c2c051896ffe = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0x49, 0x49, 0xd2, 0x07, 0xd3, 0x05, 0x50, 0x5a, 0xaf, 0xa0, 0x28, 0xbf, 0x24, 0x5f, 0x88,
	0x1d, 0x2a, 0xa8, 0x54, 0xcb, 0xc5, 0x1b, 0x94, 0x9a, 0x9c, 0x5f, 0x94, 0x92, 0x9a, 0xe2, 0x0a,
	0x12, 0x12, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xf2,
	0x74, 0x11, 0x12, 0xe3, 0x62, 0xcb, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x92, 0x60, 0x52, 0x60, 0xd4,
	0x60, 0x09, 0x82, 0xf2, 0x84, 0x64, 0xb8, 0x38, 0xc1, 0x66, 0x84, 0x54, 0x16, 0xa4, 0x4a, 0x30,
	0x83, 0x95, 0x23, 0x04, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x58, 0x14, 0x18,
	0x35, 0x78, 0x82, 0xc0, 0x6c, 0x90, 0x58, 0x6e, 0x6a, 0x49, 0xa2, 0x04, 0x2b, 0x44, 0x0c, 0xc4,
	0x76, 0xd2, 0x8e, 0xd2, 0x4c, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f,
	0x49, 0xcd, 0xac, 0xc8, 0x2c, 0xd6, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f, 0xd5, 0x47, 0xf3,
	0x40, 0x12, 0x1b, 0xd8, 0xed, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0xd3, 0xff, 0x6c,
	0xda, 0x00, 0x00, 0x00,
}
