// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventdb/eventpb/snapshot.proto

package eventpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordedSnapshot struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 []byte   `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordedSnapshot) Reset()         { *m = RecordedSnapshot{} }
func (m *RecordedSnapshot) String() string { return proto.CompactTextString(m) }
func (*RecordedSnapshot) ProtoMessage()    {}
func (*RecordedSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fd87282cbb32e41, []int{0}
}

func (m *RecordedSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordedSnapshot.Unmarshal(m, b)
}
func (m *RecordedSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordedSnapshot.Marshal(b, m, deterministic)
}
func (m *RecordedSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordedSnapshot.Merge(m, src)
}
func (m *RecordedSnapshot) XXX_Size() int {
	return xxx_messageInfo_RecordedSnapshot.Size(m)
}
func (m *RecordedSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordedSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_RecordedSnapshot proto.InternalMessageInfo

func (m *RecordedSnapshot) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RecordedSnapshot) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RecordedSnapshot) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RecordedSnapshot) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordedSnapshot)(nil), "eventpb.RecordedSnapshot")
}

func init() {
	proto.RegisterFile("eventdb/eventpb/snapshot.proto", fileDescriptor_7fd87282cbb32e41)
}

var fileDescriptor_7fd87282cbb32e41 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x46, 0x49, 0x2d, 0x15, 0x83, 0x88, 0x64, 0x90, 0x4c, 0x52, 0x9c, 0x2a, 0x42, 0x33, 0xf8,
	0x0f, 0xa4, 0x4b, 0xd7, 0xb8, 0xb9, 0x25, 0xcd, 0xd1, 0x76, 0x68, 0xaf, 0x24, 0x57, 0xf1, 0xe7,
	0x4b, 0x6b, 0x26, 0xa7, 0x7b, 0xf7, 0xf8, 0x86, 0xc7, 0xcf, 0xf0, 0x86, 0x91, 0x9c, 0x55, 0xeb,
	0x9d, 0xac, 0x0a, 0xa3, 0x99, 0x42, 0x87, 0x54, 0x4e, 0x1e, 0x09, 0xc5, 0x36, 0xfa, 0x8b, 0xe5,
	0x47, 0x0d, 0x0d, 0x7a, 0x07, 0xee, 0x19, 0x27, 0xe2, 0xc0, 0x93, 0xba, 0x92, 0x2c, 0x67, 0xc5,
	0x4e, 0x27, 0x75, 0x25, 0x4e, 0x3c, 0x1b, 0xe7, 0xc1, 0x82, 0x97, 0x49, 0xce, 0x8a, 0x54, 0xc7,
	0x4f, 0x08, 0x9e, 0x3a, 0x43, 0x46, 0x6e, 0x72, 0x56, 0xec, 0xf5, 0xca, 0x8b, 0x1b, 0x80, 0x8c,
	0x4c, 0x7f, 0x6e, 0xe1, 0xc7, 0xed, 0x75, 0x6d, 0x7b, 0xea, 0x66, 0x5b, 0x36, 0x38, 0x28, 0x07,
	0xfd, 0xa7, 0x0f, 0x2a, 0x10, 0x7a, 0xd3, 0x82, 0xfa, 0x0b, 0xb5, 0xd9, 0x1a, 0x78, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x5e, 0xd0, 0x70, 0xb4, 0xc2, 0x00, 0x00, 0x00,
}
